name: Build and Upload Docker Image

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当有 pull request 到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t jekyll:ruby_3.2 .

      - name: Save Docker image to a tar file
        run: docker save jekyll:ruby_3.2 -o jekyll_ruby_3.2.tar

      - name: Upload Docker image tar file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-tar
          path: jekyll_ruby_3.2.tar
